name: Mannual deploy

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Target environment'
        required: true
        default: 'dev'

 #     tags:
 #      description: 'Deploy-new'
jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Replace nginx site-available configuration to ${{ github.event.inputs.targetEnv }}.exlabs.cloud
        run: |
          cat envs/.${{ github.event.inputs.targetEnv }}
